//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiSpeakClientV30ac.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:55273/MDM_Server.asmx")]
        public string MultiSpeakClientV30ac_proxyMDM3ac_MDM_Server {
            get {
                return ((string)(this["MultiSpeakClientV30ac_proxyMDM3ac_MDM_Server"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:55273/MR_Server.asmx")]
        public string MultiSpeakClientV30ac_proxyMR3ac_MR_Server {
            get {
                return ((string)(this["MultiSpeakClientV30ac_proxyMR3ac_MR_Server"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:55273/OA_Server.asmx")]
        public string MultiSpeakClientV30ac_proxyOA3ac_OA_Server {
            get {
                return ((string)(this["MultiSpeakClientV30ac_proxyOA3ac_OA_Server"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:55273/CB_Server.asmx")]
        public string MultiSpeakClientV30ac_proxyCB3ac_CB_Server {
            get {
                return ((string)(this["MultiSpeakClientV30ac_proxyCB3ac_CB_Server"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:55273/OD_Server.asmx")]
        public string MultiSpeakClientV30ac_proxyOD3ac_OD_Server {
            get {
                return ((string)(this["MultiSpeakClientV30ac_proxyOD3ac_OD_Server"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:55273/EA_Server.asmx")]
        public string MultiSpeakClientV30ac_proxyEA3ac_EA_Server {
            get {
                return ((string)(this["MultiSpeakClientV30ac_proxyEA3ac_EA_Server"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://63.164.96.175/MultiSpeak416/MDM_SERVER.asmx")]
        public string MultiSpeakClientV30ac_proxyMDM416_MDM_Server {
            get {
                return ((string)(this["MultiSpeakClientV30ac_proxyMDM416_MDM_Server"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:50289/NOT_Server.asmx")]
        public string MultiSpeakClientV30ac_proxyNOT416_NOT_Server {
            get {
                return ((string)(this["MultiSpeakClientV30ac_proxyNOT416_NOT_Server"]));
            }
        }
    }
}
