INSERT INTO [dbo].[Meter]
           ([MeterIdentifier]
           ,[MeterTypeId]
           ,[ManufacturerModelId]
           ,[LocationId]
           ,[AMISerialNo]
           ,[ManufacturerSerialNumber]
           ,[MeterStatusId]
           ,[MeterNote]
           ,[PurchaseDate]
           ,[ScrapDate]
           ,[ReadSourceId]
           ,[AMRMeterType]
           ,[Created]
           ,[LastUpdated]
           ,[SourceMeterIdentifier]
           ,[DisconnectCollarSerialNumber]
           ,[DisconnectCollarType]
           ,[RecordInterval]
           ,[Dials]
           ,[ServiceTypeId]
           ,[Multiplier]
           ,[FactoryIdNo]
           ,[IsBillable]
           ,[AMIControlIdentifier]
           ,[CurrentSwitchState]
           ,[Port])
     VALUES('M2154890647',1,175,42944,'fake',null,17,null,null,null,17,'iSA4',GETDATE(),GETDATE(),null,'NONE','NONE',null,null,1,1,null,null,null,null,null)

	 
	 INSERT INTO [dbo].[Meter]
           ([MeterIdentifier]
           ,[MeterTypeId]
           ,[ManufacturerModelId]
           ,[LocationId]
           ,[AMISerialNo]
           ,[ManufacturerSerialNumber]
           ,[MeterStatusId]
           ,[MeterNote]
           ,[PurchaseDate]
           ,[ScrapDate]
           ,[ReadSourceId]
           ,[AMRMeterType]
           ,[Created]
           ,[LastUpdated]
           ,[SourceMeterIdentifier]
           ,[DisconnectCollarSerialNumber]
           ,[DisconnectCollarType]
           ,[RecordInterval]
           ,[Dials]
           ,[ServiceTypeId]
           ,[Multiplier]
           ,[FactoryIdNo]
           ,[IsBillable]
           ,[AMIControlIdentifier]
           ,[CurrentSwitchState]
           ,[Port])
     VALUES('80A10113',1,175,42944,'fake',null,17,null,null,null,17,'iSA4',GETDATE(),GETDATE(),null,'NONE','NONE',null,null,1,1,null,null,null,null,null)

	 
	 INSERT INTO [dbo].[Meter]
           ([MeterIdentifier]
           ,[MeterTypeId]
           ,[ManufacturerModelId]
           ,[LocationId]
           ,[AMISerialNo]
           ,[ManufacturerSerialNumber]
           ,[MeterStatusId]
           ,[MeterNote]
           ,[PurchaseDate]
           ,[ScrapDate]
           ,[ReadSourceId]
           ,[AMRMeterType]
           ,[Created]
           ,[LastUpdated]
           ,[SourceMeterIdentifier]
           ,[DisconnectCollarSerialNumber]
           ,[DisconnectCollarType]
           ,[RecordInterval]
           ,[Dials]
           ,[ServiceTypeId]
           ,[Multiplier]
           ,[FactoryIdNo]
           ,[IsBillable]
           ,[AMIControlIdentifier]
           ,[CurrentSwitchState]
           ,[Port])
     VALUES('M2154852990',1,175,42944,'fake',null,17,null,null,null,17,'iSA4',GETDATE(),GETDATE(),null,'NONE','NONE',null,null,1,1,null,null,null,null,null)

	 
	 INSERT INTO [dbo].[Meter]
           ([MeterIdentifier]
           ,[MeterTypeId]
           ,[ManufacturerModelId]
           ,[LocationId]
           ,[AMISerialNo]
           ,[ManufacturerSerialNumber]
           ,[MeterStatusId]
           ,[MeterNote]
           ,[PurchaseDate]
           ,[ScrapDate]
           ,[ReadSourceId]
           ,[AMRMeterType]
           ,[Created]
           ,[LastUpdated]
           ,[SourceMeterIdentifier]
           ,[DisconnectCollarSerialNumber]
           ,[DisconnectCollarType]
           ,[RecordInterval]
           ,[Dials]
           ,[ServiceTypeId]
           ,[Multiplier]
           ,[FactoryIdNo]
           ,[IsBillable]
           ,[AMIControlIdentifier]
           ,[CurrentSwitchState]
           ,[Port])
     VALUES('5019F9C8',1,175,42944,'fake',null,17,null,null,null,17,'iSA4',GETDATE(),GETDATE(),null,'NONE','NONE',null,null,1,1,null,null,null,null,null)

	 
	 INSERT INTO [dbo].[Meter]
           ([MeterIdentifier]
           ,[MeterTypeId]
           ,[ManufacturerModelId]
           ,[LocationId]
           ,[AMISerialNo]
           ,[ManufacturerSerialNumber]
           ,[MeterStatusId]
           ,[MeterNote]
           ,[PurchaseDate]
           ,[ScrapDate]
           ,[ReadSourceId]
           ,[AMRMeterType]
           ,[Created]
           ,[LastUpdated]
           ,[SourceMeterIdentifier]
           ,[DisconnectCollarSerialNumber]
           ,[DisconnectCollarType]
           ,[RecordInterval]
           ,[Dials]
           ,[ServiceTypeId]
           ,[Multiplier]
           ,[FactoryIdNo]
           ,[IsBillable]
           ,[AMIControlIdentifier]
           ,[CurrentSwitchState]
           ,[Port])
     VALUES('F0201546',1,175,42944,'fake',null,17,null,null,null,17,'iSA4',GETDATE(),GETDATE(),null,'NONE','NONE',null,null,1,1,null,null,null,null,null)

	 
	 INSERT INTO [dbo].[Meter]
           ([MeterIdentifier]
           ,[MeterTypeId]
           ,[ManufacturerModelId]
           ,[LocationId]
           ,[AMISerialNo]
           ,[ManufacturerSerialNumber]
           ,[MeterStatusId]
           ,[MeterNote]
           ,[PurchaseDate]
           ,[ScrapDate]
           ,[ReadSourceId]
           ,[AMRMeterType]
           ,[Created]
           ,[LastUpdated]
           ,[SourceMeterIdentifier]
           ,[DisconnectCollarSerialNumber]
           ,[DisconnectCollarType]
           ,[RecordInterval]
           ,[Dials]
           ,[ServiceTypeId]
           ,[Multiplier]
           ,[FactoryIdNo]
           ,[IsBillable]
           ,[AMIControlIdentifier]
           ,[CurrentSwitchState]
           ,[Port])
     VALUES('AnthonyMIFTestK',1,175,42944,'fake',null,17,null,null,null,17,'iSA4',GETDATE(),GETDATE(),null,'NONE','NONE',null,null,1,1,null,null,null,null,null)

	 
	 INSERT INTO [dbo].[Meter]
           ([MeterIdentifier]
           ,[MeterTypeId]
           ,[ManufacturerModelId]
           ,[LocationId]
           ,[AMISerialNo]
           ,[ManufacturerSerialNumber]
           ,[MeterStatusId]
           ,[MeterNote]
           ,[PurchaseDate]
           ,[ScrapDate]
           ,[ReadSourceId]
           ,[AMRMeterType]
           ,[Created]
           ,[LastUpdated]
           ,[SourceMeterIdentifier]
           ,[DisconnectCollarSerialNumber]
           ,[DisconnectCollarType]
           ,[RecordInterval]
           ,[Dials]
           ,[ServiceTypeId]
           ,[Multiplier]
           ,[FactoryIdNo]
           ,[IsBillable]
           ,[AMIControlIdentifier]
           ,[CurrentSwitchState]
           ,[Port])
     VALUES('F0091875',1,175,42944,'fake',null,17,null,null,null,17,'iSA4',GETDATE(),GETDATE(),null,'NONE','NONE',null,null,1,1,null,null,null,null,null)

	 
	 INSERT INTO [dbo].[Meter]
           ([MeterIdentifier]
           ,[MeterTypeId]
           ,[ManufacturerModelId]
           ,[LocationId]
           ,[AMISerialNo]
           ,[ManufacturerSerialNumber]
           ,[MeterStatusId]
           ,[MeterNote]
           ,[PurchaseDate]
           ,[ScrapDate]
           ,[ReadSourceId]
           ,[AMRMeterType]
           ,[Created]
           ,[LastUpdated]
           ,[SourceMeterIdentifier]
           ,[DisconnectCollarSerialNumber]
           ,[DisconnectCollarType]
           ,[RecordInterval]
           ,[Dials]
           ,[ServiceTypeId]
           ,[Multiplier]
           ,[FactoryIdNo]
           ,[IsBillable]
           ,[AMIControlIdentifier]
           ,[CurrentSwitchState]
           ,[Port])
     VALUES('F07DF930',1,175,42944,'fake',null,17,null,null,null,17,'iSA4',GETDATE(),GETDATE(),null,'NONE','NONE',null,null,1,1,null,null,null,null,null)

	 
	 INSERT INTO [dbo].[Meter]
           ([MeterIdentifier]
           ,[MeterTypeId]
           ,[ManufacturerModelId]
           ,[LocationId]
           ,[AMISerialNo]
           ,[ManufacturerSerialNumber]
           ,[MeterStatusId]
           ,[MeterNote]
           ,[PurchaseDate]
           ,[ScrapDate]
           ,[ReadSourceId]
           ,[AMRMeterType]
           ,[Created]
           ,[LastUpdated]
           ,[SourceMeterIdentifier]
           ,[DisconnectCollarSerialNumber]
           ,[DisconnectCollarType]
           ,[RecordInterval]
           ,[Dials]
           ,[ServiceTypeId]
           ,[Multiplier]
           ,[FactoryIdNo]
           ,[IsBillable]
           ,[AMIControlIdentifier]
           ,[CurrentSwitchState]
           ,[Port])
     VALUES('D004018C',1,175,42944,'fake',null,17,null,null,null,17,'iSA4',GETDATE(),GETDATE(),null,'NONE','NONE',null,null,1,1,null,null,null,null,null)

	 
	 INSERT INTO [dbo].[Meter]
           ([MeterIdentifier]
           ,[MeterTypeId]
           ,[ManufacturerModelId]
           ,[LocationId]
           ,[AMISerialNo]
           ,[ManufacturerSerialNumber]
           ,[MeterStatusId]
           ,[MeterNote]
           ,[PurchaseDate]
           ,[ScrapDate]
           ,[ReadSourceId]
           ,[AMRMeterType]
           ,[Created]
           ,[LastUpdated]
           ,[SourceMeterIdentifier]
           ,[DisconnectCollarSerialNumber]
           ,[DisconnectCollarType]
           ,[RecordInterval]
           ,[Dials]
           ,[ServiceTypeId]
           ,[Multiplier]
           ,[FactoryIdNo]
           ,[IsBillable]
           ,[AMIControlIdentifier]
           ,[CurrentSwitchState]
           ,[Port])
     VALUES('M2154890663',1,175,42944,'fake',null,17,null,null,null,17,'iSA4',GETDATE(),GETDATE(),null,'NONE','NONE',null,null,1,1,null,null,null,null,null)

	 
	 INSERT INTO [dbo].[Meter]
           ([MeterIdentifier]
           ,[MeterTypeId]
           ,[ManufacturerModelId]
           ,[LocationId]
           ,[AMISerialNo]
           ,[ManufacturerSerialNumber]
           ,[MeterStatusId]
           ,[MeterNote]
           ,[PurchaseDate]
           ,[ScrapDate]
           ,[ReadSourceId]
           ,[AMRMeterType]
           ,[Created]
           ,[LastUpdated]
           ,[SourceMeterIdentifier]
           ,[DisconnectCollarSerialNumber]
           ,[DisconnectCollarType]
           ,[RecordInterval]
           ,[Dials]
           ,[ServiceTypeId]
           ,[Multiplier]
           ,[FactoryIdNo]
           ,[IsBillable]
           ,[AMIControlIdentifier]
           ,[CurrentSwitchState]
           ,[Port])
     VALUES('M2154890648',1,175,42944,'fake',null,17,null,null,null,17,'iSA4',GETDATE(),GETDATE(),null,'NONE','NONE',null,null,1,1,null,null,null,null,null)

	 
----------------------------------

	 INSERT INTO [dbo].[Meter]
           ([MeterIdentifier]
           ,[MeterTypeId]
           ,[ManufacturerModelId]
           ,[LocationId]
           ,[AMISerialNo]
           ,[ManufacturerSerialNumber]
           ,[MeterStatusId]
           ,[MeterNote]
           ,[PurchaseDate]
           ,[ScrapDate]
           ,[ReadSourceId]
           ,[AMRMeterType]
           ,[Created]
           ,[LastUpdated]
           ,[SourceMeterIdentifier]
           ,[DisconnectCollarSerialNumber]
           ,[DisconnectCollarType]
           ,[RecordInterval]
           ,[Dials]
           ,[ServiceTypeId]
           ,[Multiplier]
           ,[FactoryIdNo]
           ,[IsBillable]
           ,[AMIControlIdentifier]
           ,[CurrentSwitchState]
           ,[Port])
     VALUES('F016CB40',1,175,42944,'fake',null,17,null,null,null,17,'iSA4',GETDATE(),GETDATE(),null,'NONE','NONE',null,null,1,1,null,null,null,null,null)

	 


	 INSERT INTO [dbo].[Meter]
           ([MeterIdentifier]
           ,[MeterTypeId]
           ,[ManufacturerModelId]
           ,[LocationId]
           ,[AMISerialNo]
           ,[ManufacturerSerialNumber]
           ,[MeterStatusId]
           ,[MeterNote]
           ,[PurchaseDate]
           ,[ScrapDate]
           ,[ReadSourceId]
           ,[AMRMeterType]
           ,[Created]
           ,[LastUpdated]
           ,[SourceMeterIdentifier]
           ,[DisconnectCollarSerialNumber]
           ,[DisconnectCollarType]
           ,[RecordInterval]
           ,[Dials]
           ,[ServiceTypeId]
           ,[Multiplier]
           ,[FactoryIdNo]
           ,[IsBillable]
           ,[AMIControlIdentifier]
           ,[CurrentSwitchState]
           ,[Port])
     VALUES('LG101182279',1,175,42944,'fake',null,17,null,null,null,17,'iSA4',GETDATE(),GETDATE(),null,'NONE','NONE',null,null,1,1,null,null,null,null,null)

	 




	 INSERT INTO [dbo].[Meter]
           ([MeterIdentifier]
           ,[MeterTypeId]
           ,[ManufacturerModelId]
           ,[LocationId]
           ,[AMISerialNo]
           ,[ManufacturerSerialNumber]
           ,[MeterStatusId]
           ,[MeterNote]
           ,[PurchaseDate]
           ,[ScrapDate]
           ,[ReadSourceId]
           ,[AMRMeterType]
           ,[Created]
           ,[LastUpdated]
           ,[SourceMeterIdentifier]
           ,[DisconnectCollarSerialNumber]
           ,[DisconnectCollarType]
           ,[RecordInterval]
           ,[Dials]
           ,[ServiceTypeId]
           ,[Multiplier]
           ,[FactoryIdNo]
           ,[IsBillable]
           ,[AMIControlIdentifier]
           ,[CurrentSwitchState]
           ,[Port])
     VALUES('LG901182274',1,175,42944,'fake',null,17,null,null,null,17,'iSA4',GETDATE(),GETDATE(),null,'NONE','NONE',null,null,1,1,null,null,null,null,null)

	
	 INSERT INTO [dbo].[Meter]
           ([MeterIdentifier]
           ,[MeterTypeId]
           ,[ManufacturerModelId]
           ,[LocationId]
           ,[AMISerialNo]
           ,[ManufacturerSerialNumber]
           ,[MeterStatusId]
           ,[MeterNote]
           ,[PurchaseDate]
           ,[ScrapDate]
           ,[ReadSourceId]
           ,[AMRMeterType]
           ,[Created]
           ,[LastUpdated]
           ,[SourceMeterIdentifier]
           ,[DisconnectCollarSerialNumber]
           ,[DisconnectCollarType]
           ,[RecordInterval]
           ,[Dials]
           ,[ServiceTypeId]
           ,[Multiplier]
           ,[FactoryIdNo]
           ,[IsBillable]
           ,[AMIControlIdentifier]
           ,[CurrentSwitchState]
           ,[Port])
     VALUES('500D5B74',1,175,42944,'fake',null,17,null,null,null,17,'iSA4',GETDATE(),GETDATE(),null,'NONE','NONE',null,null,1,1,null,null,null,null,null)

	  	 INSERT INTO [dbo].[Meter]
           ([MeterIdentifier]
           ,[MeterTypeId]
           ,[ManufacturerModelId]
           ,[LocationId]
           ,[AMISerialNo]
           ,[ManufacturerSerialNumber]
           ,[MeterStatusId]
           ,[MeterNote]
           ,[PurchaseDate]
           ,[ScrapDate]
           ,[ReadSourceId]
           ,[AMRMeterType]
           ,[Created]
           ,[LastUpdated]
           ,[SourceMeterIdentifier]
           ,[DisconnectCollarSerialNumber]
           ,[DisconnectCollarType]
           ,[RecordInterval]
           ,[Dials]
           ,[ServiceTypeId]
           ,[Multiplier]
           ,[FactoryIdNo]
           ,[IsBillable]
           ,[AMIControlIdentifier]
           ,[CurrentSwitchState]
           ,[Port])
     VALUES('F03275F6',1,175,42944,'fake',null,17,null,null,null,17,'iSA4',GETDATE(),GETDATE(),null,'NONE','NONE',null,null,1,1,null,null,null,null,null)


	  	 INSERT INTO [dbo].[Meter]
           ([MeterIdentifier]
           ,[MeterTypeId]
           ,[ManufacturerModelId]
           ,[LocationId]
           ,[AMISerialNo]
           ,[ManufacturerSerialNumber]
           ,[MeterStatusId]
           ,[MeterNote]
           ,[PurchaseDate]
           ,[ScrapDate]
           ,[ReadSourceId]
           ,[AMRMeterType]
           ,[Created]
           ,[LastUpdated]
           ,[SourceMeterIdentifier]
           ,[DisconnectCollarSerialNumber]
           ,[DisconnectCollarType]
           ,[RecordInterval]
           ,[Dials]
           ,[ServiceTypeId]
           ,[Multiplier]
           ,[FactoryIdNo]
           ,[IsBillable]
           ,[AMIControlIdentifier]
           ,[CurrentSwitchState]
           ,[Port])
     VALUES('40BC4175',1,175,42944,'fake',null,17,null,null,null,17,'iSA4',GETDATE(),GETDATE(),null,'NONE','NONE',null,null,1,1,null,null,null,null,null)



	  	 INSERT INTO [dbo].[Meter]
           ([MeterIdentifier]
           ,[MeterTypeId]
           ,[ManufacturerModelId]
           ,[LocationId]
           ,[AMISerialNo]
           ,[ManufacturerSerialNumber]
           ,[MeterStatusId]
           ,[MeterNote]
           ,[PurchaseDate]
           ,[ScrapDate]
           ,[ReadSourceId]
           ,[AMRMeterType]
           ,[Created]
           ,[LastUpdated]
           ,[SourceMeterIdentifier]
           ,[DisconnectCollarSerialNumber]
           ,[DisconnectCollarType]
           ,[RecordInterval]
           ,[Dials]
           ,[ServiceTypeId]
           ,[Multiplier]
           ,[FactoryIdNo]
           ,[IsBillable]
           ,[AMIControlIdentifier]
           ,[CurrentSwitchState]
           ,[Port])
     VALUES('81200634',1,175,42944,'fake',null,17,null,null,null,17,'iSA4',GETDATE(),GETDATE(),null,'NONE','NONE',null,null,1,1,null,null,null,null,null)


	  	 INSERT INTO [dbo].[Meter]
           ([MeterIdentifier]
           ,[MeterTypeId]
           ,[ManufacturerModelId]
           ,[LocationId]
           ,[AMISerialNo]
           ,[ManufacturerSerialNumber]
           ,[MeterStatusId]
           ,[MeterNote]
           ,[PurchaseDate]
           ,[ScrapDate]
           ,[ReadSourceId]
           ,[AMRMeterType]
           ,[Created]
           ,[LastUpdated]
           ,[SourceMeterIdentifier]
           ,[DisconnectCollarSerialNumber]
           ,[DisconnectCollarType]
           ,[RecordInterval]
           ,[Dials]
           ,[ServiceTypeId]
           ,[Multiplier]
           ,[FactoryIdNo]
           ,[IsBillable]
           ,[AMIControlIdentifier]
           ,[CurrentSwitchState]
           ,[Port])
     VALUES('10710000',1,175,42944,'fake',null,17,null,null,null,17,'iSA4',GETDATE(),GETDATE(),null,'NONE','NONE',null,null,1,1,null,null,null,null,null)


	  	 INSERT INTO [dbo].[Meter]
           ([MeterIdentifier]
           ,[MeterTypeId]
           ,[ManufacturerModelId]
           ,[LocationId]
           ,[AMISerialNo]
           ,[ManufacturerSerialNumber]
           ,[MeterStatusId]
           ,[MeterNote]
           ,[PurchaseDate]
           ,[ScrapDate]
           ,[ReadSourceId]
           ,[AMRMeterType]
           ,[Created]
           ,[LastUpdated]
           ,[SourceMeterIdentifier]
           ,[DisconnectCollarSerialNumber]
           ,[DisconnectCollarType]
           ,[RecordInterval]
           ,[Dials]
           ,[ServiceTypeId]
           ,[Multiplier]
           ,[FactoryIdNo]
           ,[IsBillable]
           ,[AMIControlIdentifier]
           ,[CurrentSwitchState]
           ,[Port])
     VALUES('00101',1,175,42944,'fake',null,17,null,null,null,17,'iSA4',GETDATE(),GETDATE(),null,'NONE','NONE',null,null,1,1,null,null,null,null,null)


	  	 INSERT INTO [dbo].[Meter]
           ([MeterIdentifier]
           ,[MeterTypeId]
           ,[ManufacturerModelId]
           ,[LocationId]
           ,[AMISerialNo]
           ,[ManufacturerSerialNumber]
           ,[MeterStatusId]
           ,[MeterNote]
           ,[PurchaseDate]
           ,[ScrapDate]
           ,[ReadSourceId]
           ,[AMRMeterType]
           ,[Created]
           ,[LastUpdated]
           ,[SourceMeterIdentifier]
           ,[DisconnectCollarSerialNumber]
           ,[DisconnectCollarType]
           ,[RecordInterval]
           ,[Dials]
           ,[ServiceTypeId]
           ,[Multiplier]
           ,[FactoryIdNo]
           ,[IsBillable]
           ,[AMIControlIdentifier]
           ,[CurrentSwitchState]
           ,[Port])
     VALUES('F033C324',1,175,42944,'fake',null,17,null,null,null,17,'iSA4',GETDATE(),GETDATE(),null,'NONE','NONE',null,null,1,1,null,null,null,null,null)


	  	 INSERT INTO [dbo].[Meter]
           ([MeterIdentifier]
           ,[MeterTypeId]
           ,[ManufacturerModelId]
           ,[LocationId]
           ,[AMISerialNo]
           ,[ManufacturerSerialNumber]
           ,[MeterStatusId]
           ,[MeterNote]
           ,[PurchaseDate]
           ,[ScrapDate]
           ,[ReadSourceId]
           ,[AMRMeterType]
           ,[Created]
           ,[LastUpdated]
           ,[SourceMeterIdentifier]
           ,[DisconnectCollarSerialNumber]
           ,[DisconnectCollarType]
           ,[RecordInterval]
           ,[Dials]
           ,[ServiceTypeId]
           ,[Multiplier]
           ,[FactoryIdNo]
           ,[IsBillable]
           ,[AMIControlIdentifier]
           ,[CurrentSwitchState]
           ,[Port])
     VALUES('F06C60B1',1,175,42944,'fake',null,17,null,null,null,17,'iSA4',GETDATE(),GETDATE(),null,'NONE','NONE',null,null,1,1,null,null,null,null,null)



















